/* File generated by app - do not edit! */
/* #################################### */
/* Types and attributes for the document type Annot */

/* Global attributes */
#define Annot_ATTR_Language 1

/* Local attributes */
#define Annot_ATTR_XmlBody 2
#define Annot_ATTR_XmlBody_VAL_Yes_ 1
#define Annot_ATTR_Charset 3
#define Annot_ATTR_HREF_ 4
#define Annot_ATTR_isReply 5
#define Annot_ATTR_isReply_VAL_YES_ 1
#define Annot_ATTR_isReply_VAL_NO_ 2
#define Annot_ATTR_Annot_HREF_ 6
#define Annot_ATTR_Orphan_item 7
#define Annot_ATTR_Orphan_item_VAL_Yes_ 1
#define Annot_ATTR_Selected_ 8
#define Annot_ATTR_Selected__VAL_Yes_ 1

/* Basic elements */
#define Annot_EL_TEXT_UNIT 1
#define Annot_EL_GRAPHICS_UNIT 2
#define Annot_EL_SYMBOL_UNIT 3
#define Annot_EL_PICTURE_UNIT 4
#define Annot_EL_PAGE_BREAK 6
#define Annot_EL_ANY_TYPE 7

/* Elements */
#define Annot_EL_Document 8
#define Annot_EL_C_Empty 9
#define Annot_EL_Annot 10
#define Annot_EL_Body 11
#define Annot_EL_Description 12
#define Annot_EL_ATitle 13
#define Annot_EL_Author 14
#define Annot_EL_CreatorEmail 15
#define Annot_EL_CreatorGivenName 16
#define Annot_EL_CreatorFamilyName 17
#define Annot_EL_SourceDoc 18
#define Annot_EL_RDFtype 19
#define Annot_EL_AnnotCDate 20
#define Annot_EL_AnnotMDate 21
#define Annot_EL_Thread 22
#define Annot_EL_Thread_item 23
#define Annot_EL_TI_content 24
#define Annot_EL_TI_desc 25
#define Annot_EL_TI_Title 26
#define Annot_EL_TI_Date 27
#define Annot_EL_TI_Author 28
#define Annot_EL_TI_Type 29

/* Imported natures */
#define Annot_EL_HTML 30
#define Annot_EL_MathML 31
#define Annot_EL_SVG 32
#define Annot_EL_XML 33
#define Annot_EL_TextFile 34
